[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_program = "3JAqyRbH1ripdAE8h7UrK1TKc84yyNw9QtDqHNVMQcz4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
