//! IDL ingestion for testsvm.
//!
//! One [`IdlSource`] impl per IDL format normalizes that format into a common
//! instruction model ([`IxDef`]); [`emit_client`] generates the named bundle +
//! alias client from the model, so the generator is written once and every
//! framework that emits an IDL (Quasar today, Shank/Codama next) is a parser,
//! not a fork of the codegen.
//!
//! The generated client, per flat-args instruction, is a struct whose fields
//! are the declared accounts (well-known programs injected, not exposed) and the
//! scalar args, with:
//!
//!   - `ix()`     : the `Instruction`, accounts in IDL order with the IDL's
//!                  signer/writable flags, the discriminator, args little-endian
//!                  encoded, then `remaining_accounts` appended.
//!   - `alias_all`: registers each account field under its IDL name on any
//!                  [`TestSVM`](testsvm::TestSVM) backend (the engine-agnostic
//!                  AliasMirror).
//!
//! Instructions with a non-scalar arg are skipped at the encoding boundary
//! (wincode `DynVec`/`DynBytes`, borsh `Vec`/`String`): the flat-args floor.

use std::fmt::Write as _;

/// A parsed IDL, normalized: the program address and its instructions. One impl
/// per IDL format (see [`quasar::QuasarIdl`]).
pub trait IdlSource {
    /// The program's on-chain address, base58.
    fn program_address(&self) -> &str;
    /// The instructions, in declaration order.
    fn instructions(&self) -> Vec<IxDef>;
}

/// One instruction, format-independent.
#[derive(Debug, Clone)]
pub struct IxDef {
    pub name: String,
    /// The leading-byte discriminator (any width).
    pub discriminator: Vec<u8>,
    /// The declared accounts, in the order the instruction lists them.
    pub accounts: Vec<AccountDef>,
    pub args: Vec<ArgDef>,
    /// Whether a variable `remaining_accounts` tail is appended.
    pub has_remaining: bool,
}

#[derive(Debug, Clone)]
pub struct AccountDef {
    pub name: String,
    pub signer: bool,
    pub writable: bool,
}

#[derive(Debug, Clone)]
pub struct ArgDef {
    pub name: String,
    pub ty: ArgType,
}

/// The arg types the flat-args floor handles, plus the catch-all that pushes an
/// instruction past the boundary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ArgType {
    U8,
    U16,
    U32,
    U64,
    I8,
    I16,
    I32,
    I64,
    Bool,
    Pubkey,
    /// Anything not flat (a string, a vec, a defined type): the encoding
    /// boundary. Carries the source spelling for the skip diagnostic.
    Unsupported(String),
}

impl ArgType {
    /// The Rust type for a struct field, or `None` past the boundary.
    pub fn rust_type(&self) -> Option<&'static str> {
        Some(match self {
            ArgType::U8 => "u8",
            ArgType::U16 => "u16",
            ArgType::U32 => "u32",
            ArgType::U64 => "u64",
            ArgType::I8 => "i8",
            ArgType::I16 => "i16",
            ArgType::I32 => "i32",
            ArgType::I64 => "i64",
            ArgType::Bool => "bool",
            ArgType::Pubkey => "Pubkey",
            ArgType::Unsupported(_) => return None,
        })
    }

    /// The statement that appends this arg's little-endian bytes to `data`,
    /// given the field access `f` (e.g. `self.amount`).
    fn encode(&self, f: &str) -> Option<String> {
        Some(match self {
            ArgType::Bool => format!("data.push({f} as u8);"),
            ArgType::Pubkey => format!("data.extend_from_slice({f}.as_ref());"),
            ArgType::Unsupported(_) => return None,
            // Every integer is little-endian, which is both wincode's and
            // borsh's scalar encoding, so this is format-independent.
            _ => format!("data.extend_from_slice(&{f}.to_le_bytes());"),
        })
    }
}

/// Generate the client module source from any IDL source.
pub fn emit_client(src: &dyn IdlSource) -> String {
    let mut out = String::new();
    out.push_str(
        "//! GENERATED by testsvm-idl. Do not edit by hand; re-run the generator.\n\
         //! Each struct's `ix()` lays accounts out in IDL order with the IDL's\n\
         //! signer/writable flags, the discriminator, and little-endian args;\n\
         //! `alias_all` names the accounts on any TestSVM backend.\n\
         #![allow(dead_code, unused_imports)]\n\n\
         use {\n    solana_instruction::{AccountMeta, Instruction},\n    \
         solana_pubkey::Pubkey,\n    std::str::FromStr,\n    testsvm::TestSVM,\n};\n\n",
    );
    let _ = writeln!(
        out,
        "pub fn program_id() -> Pubkey {{ Pubkey::from_str(\"{}\").unwrap() }}",
        src.program_address()
    );
    out.push_str(WELL_KNOWN_FNS);
    out.push('\n');

    for ix in src.instructions() {
        if let Some(bad) = ix.args.iter().find(|a| a.ty.rust_type().is_none()) {
            let spelling = match &bad.ty {
                ArgType::Unsupported(s) => s.as_str(),
                _ => "?",
            };
            let _ = writeln!(
                out,
                "// SKIPPED `{}`: non-scalar arg `{}` ({}) — the flat-args boundary.\n",
                ix.name, bad.name, spelling
            );
            continue;
        }
        emit_instruction(&mut out, &ix);
    }
    out
}

fn emit_instruction(out: &mut String, ix: &IxDef) {
    let name = pascal(&ix.name);
    let fields: Vec<&AccountDef> = ix
        .accounts
        .iter()
        .filter(|a| injector(&a.name).is_none())
        .collect();

    // struct
    let _ = writeln!(out, "pub struct {name} {{");
    for a in &fields {
        let _ = writeln!(out, "    pub {}: Pubkey,", snake(&a.name));
    }
    for arg in &ix.args {
        let _ = writeln!(out, "    pub {}: {},", snake(&arg.name), arg.ty.rust_type().unwrap());
    }
    if ix.has_remaining {
        out.push_str("    /// Appended after the declared accounts, in order.\n");
        out.push_str("    pub remaining: Vec<AccountMeta>,\n");
    }
    out.push_str("}\n\n");

    // impl
    let _ = writeln!(out, "impl {name} {{");
    out.push_str("    pub fn ix(&self) -> Instruction {\n");
    let mutability = if ix.has_remaining { "let mut accounts" } else { "let accounts" };
    let _ = writeln!(out, "        {mutability} = vec![");
    for a in &ix.accounts {
        let pk = match injector(&a.name) {
            Some(inject) => inject.to_string(),
            None => format!("self.{}", snake(&a.name)),
        };
        let _ = writeln!(out, "            {},", meta(&pk, a.signer, a.writable));
    }
    out.push_str("        ];\n");
    if ix.has_remaining {
        out.push_str("        accounts.extend(self.remaining.iter().cloned());\n");
    }
    let disc = ix
        .discriminator
        .iter()
        .map(|b| format!("{b}u8"))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "        let mut data = vec![{disc}];");
    for arg in &ix.args {
        let _ = writeln!(out, "        {}", arg.ty.encode(&format!("self.{}", snake(&arg.name))).unwrap());
    }
    out.push_str("        Instruction { program_id: program_id(), accounts, data }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn alias_all(&self, backend: &mut impl TestSVM) {\n");
    for a in &fields {
        let _ = writeln!(
            out,
            "        backend.register_alias(&self.{}, \"{}\");",
            snake(&a.name),
            pascal(&a.name)
        );
    }
    out.push_str("    }\n}\n\n");
}

const WELL_KNOWN_FNS: &str = "\
fn system_program() -> Pubkey { Pubkey::from_str(\"11111111111111111111111111111111\").unwrap() }
fn rent_sysvar() -> Pubkey { Pubkey::from_str(\"SysvarRent111111111111111111111111111111111\").unwrap() }
fn token_program() -> Pubkey { Pubkey::from_str(\"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA\").unwrap() }
fn associated_token_program() -> Pubkey { Pubkey::from_str(\"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL\").unwrap() }
";

/// A well-known account name -> the injector call emitted for it (filled from a
/// constant rather than exposed as a struct field, the way a bundle injects a
/// `Program`).
fn injector(account: &str) -> Option<&'static str> {
    match account {
        "systemProgram" | "system_program" => Some("system_program()"),
        "rent" => Some("rent_sysvar()"),
        "tokenProgram" | "token_program" => Some("token_program()"),
        "associatedTokenProgram" | "associated_token_program" => Some("associated_token_program()"),
        _ => None,
    }
}

fn meta(pk: &str, signer: bool, writable: bool) -> String {
    if writable {
        format!("AccountMeta::new({pk}, {signer})")
    } else {
        format!("AccountMeta::new_readonly({pk}, {signer})")
    }
}

fn pascal(name: &str) -> String {
    name.split(|c| c == '_' || c == '-')
        .flat_map(split_camel)
        .map(|w| {
            let mut cs = w.chars();
            match cs.next() {
                Some(c) => c.to_ascii_uppercase().to_string() + &cs.as_str().to_ascii_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else if c == '-' {
            out.push('_');
        } else {
            out.push(c);
        }
    }
    out
}

/// Split a camelCase word so `systemProgram` pascal-cases to `SystemProgram`.
fn split_camel(w: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut cur = String::new();
    for c in w.chars() {
        if c.is_ascii_uppercase() && !cur.is_empty() {
            parts.push(std::mem::take(&mut cur));
        }
        cur.push(c);
    }
    if !cur.is_empty() {
        parts.push(cur);
    }
    parts
}

/// The Quasar IDL format: the JSON `quasar idl` emits.
pub mod quasar {
    use {
        super::{AccountDef, ArgDef, ArgType, IdlSource, IxDef},
        serde::Deserialize,
    };

    #[derive(Deserialize)]
    struct RawIdl {
        address: String,
        instructions: Vec<RawIx>,
    }

    #[derive(Deserialize)]
    struct RawIx {
        name: String,
        discriminator: Vec<u8>,
        accounts: Vec<RawAcct>,
        #[serde(default)]
        args: Vec<RawArg>,
        #[serde(rename = "remainingAccounts", default)]
        remaining: Option<serde_json::Value>,
    }

    #[derive(Deserialize)]
    struct RawAcct {
        name: String,
        #[serde(default)]
        signer: bool,
        #[serde(default)]
        writable: bool,
    }

    #[derive(Deserialize)]
    struct RawArg {
        name: String,
        #[serde(rename = "type")]
        ty: serde_json::Value,
    }

    /// A parsed Quasar IDL.
    pub struct QuasarIdl {
        address: String,
        instructions: Vec<IxDef>,
    }

    impl QuasarIdl {
        pub fn from_json(json: &str) -> serde_json::Result<Self> {
            let raw: RawIdl = serde_json::from_str(json)?;
            let instructions = raw
                .instructions
                .into_iter()
                .map(|ix| IxDef {
                    name: ix.name,
                    discriminator: ix.discriminator,
                    has_remaining: ix.remaining.is_some(),
                    accounts: ix
                        .accounts
                        .into_iter()
                        .map(|a| AccountDef {
                            name: a.name,
                            signer: a.signer,
                            writable: a.writable,
                        })
                        .collect(),
                    args: ix
                        .args
                        .into_iter()
                        .map(|a| ArgDef {
                            name: a.name,
                            ty: arg_type(&a.ty),
                        })
                        .collect(),
                })
                .collect();
            Ok(QuasarIdl {
                address: raw.address,
                instructions,
            })
        }
    }

    impl IdlSource for QuasarIdl {
        fn program_address(&self) -> &str {
            &self.address
        }
        fn instructions(&self) -> Vec<IxDef> {
            self.instructions.clone()
        }
    }

    fn arg_type(v: &serde_json::Value) -> ArgType {
        match v.as_str() {
            Some("u8") => ArgType::U8,
            Some("u16") => ArgType::U16,
            Some("u32") => ArgType::U32,
            Some("u64") => ArgType::U64,
            Some("i8") => ArgType::I8,
            Some("i16") => ArgType::I16,
            Some("i32") => ArgType::I32,
            Some("i64") => ArgType::I64,
            Some("bool") => ArgType::Bool,
            Some("pubkey") | Some("publicKey") => ArgType::Pubkey,
            _ => ArgType::Unsupported(v.to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const MINI: &str = r#"{
        "address": "44444444444444444444444444444444444444444444",
        "instructions": [
            { "name": "create", "discriminator": [0],
              "accounts": [
                {"name":"creator","signer":true,"writable":true},
                {"name":"config","writable":true},
                {"name":"systemProgram"}],
              "args": [{"name":"threshold","type":"u8"}],
              "remainingAccounts": {"kind":"append"} },
            { "name": "set_label", "discriminator": [2],
              "accounts": [{"name":"config","writable":true}],
              "args": [{"name":"label","type":"string"}] }
        ]
    }"#;

    #[test]
    fn quasar_flat_args_emit_the_expected_shape() {
        let idl = quasar::QuasarIdl::from_json(MINI).unwrap();
        let out = emit_client(&idl);

        // The flat instruction becomes a named struct: declared accounts as
        // fields, the well-known program injected (not a field), the arg typed,
        // and a remaining tail.
        assert!(out.contains("pub struct Create {"), "{out}");
        assert!(out.contains("pub creator: Pubkey,"));
        assert!(out.contains("pub config: Pubkey,"));
        assert!(!out.contains("pub system_program: Pubkey,"), "well-known injected, not a field");
        assert!(out.contains("pub threshold: u8,"));
        assert!(out.contains("pub remaining: Vec<AccountMeta>,"));
        // ix() injects the program and discriminator-prefixes the data.
        assert!(out.contains("AccountMeta::new_readonly(system_program(), false)"));
        assert!(out.contains("let mut data = vec![0u8];"));
        assert!(out.contains("data.extend_from_slice(&self.threshold.to_le_bytes());"));
        // alias_all names the declared accounts.
        assert!(out.contains("backend.register_alias(&self.config, \"Config\");"));
        // The non-scalar instruction is skipped at the boundary.
        assert!(out.contains("// SKIPPED `set_label`"), "{out}");
        assert!(!out.contains("pub struct SetLabel"));
    }
}
